[2021-10-18 22:23:12,503][INFO][4447903232][main.py:88]SSRSpeed 1.01, Web Api Version 0.5.2
[2021-10-18 22:23:12,504][INFO][4447903232][requirements_check.py:73]Checking libsodium.
[2021-10-18 22:23:15,032][INFO][4447903232][requirements_check.py:57]Checking ./clients/v2ray-core/v2ctl
[2021-10-18 22:23:15,033][INFO][4447903232][requirements_check.py:57]Checking ./clients/v2ray-core/v2ray
[2021-10-18 22:23:15,036][INFO][4447903232][requirements_check.py:123]Shadowsocks-libev found /usr/local/bin/ss-local
[2021-10-18 22:23:15,036][INFO][4447903232][requirements_check.py:120]Obfs-Local found /usr/local/bin/obfs-local
[2021-10-18 22:23:15,037][INFO][4447903232][config_parser.py:176]Reading https://free.v2rss.ml/api/v1/client/subscribe?token=1ea0baf4358ed2719e89aed2c7ce0f03
[2021-10-18 22:23:18,072][INFO][4447903232][config_parser.py:102]Try V2RayN Parser.
[2021-10-18 22:23:18,074][INFO][4447903232][config_parser.py:102]Try V2RayN Parser.
[2021-10-18 22:23:18,076][WARNING][4447903232][config_parser.py:122]Unsupport link: 
[2021-10-18 22:23:18,100][INFO][4447903232][config_parser.py:152]netflix - 香港
[2021-10-18 22:23:18,100][INFO][4447903232][config_parser.py:152]netflix - 香港02
[2021-10-18 22:23:18,100][INFO][4447903232][config_parser.py:152]netflix - 美国加利福利亚|中转|枣庄
[2021-10-18 22:23:18,100][INFO][4447903232][config_parser.py:152]netflix - TripodCloud CN2GIA | 三网| 中转
[2021-10-18 22:23:18,100][INFO][4447903232][config_parser.py:152]netflix - 西伯利亚 | 中转|枣庄
[2021-10-18 22:23:18,101][INFO][4447903232][config_parser.py:152]netflix - 南非-ss | 三网 |中转枣庄
[2021-10-18 22:23:18,101][INFO][4447903232][config_parser.py:152]netflix - 美国圣何塞①  | 中转 |枣庄
[2021-10-18 22:23:18,101][INFO][4447903232][config_parser.py:152]netflix - 美国洛杉矶② |枣庄中转
[2021-10-18 22:23:18,101][INFO][4447903232][config_parser.py:152]netflix - 美国洛杉矶③  | 枣庄中转
[2021-10-18 22:23:18,101][INFO][4447903232][config_parser.py:152]netflix - 南非-ss | 三网 |解锁奈飞| 直连
[2021-10-18 22:23:18,101][INFO][4447903232][config_parser.py:152]netflix - 香港vm①ss | 三网 | 解锁奈飞| 直连
[2021-10-18 22:23:18,102][INFO][4447903232][config_parser.py:152]netflix - 香港vm②V2 | 三网 | 解锁奈飞| 直连
[2021-10-18 22:23:18,102][INFO][4447903232][config_parser.py:152]netflix - 西伯利亚 | 解锁奈飞| 直连
[2021-10-18 22:23:18,102][INFO][4447903232][config_parser.py:152]netflix - TripodCloud CN2GIA | 三网| 直连
[2021-10-18 22:23:18,102][INFO][4447903232][config_parser.py:152]netflix - 美国圣何塞① | 联通| 直连
[2021-10-18 22:23:18,102][INFO][4447903232][config_parser.py:152]netflix - 美国洛杉矶② | 联通| 直连
[2021-10-18 22:23:18,102][INFO][4447903232][config_parser.py:152]netflix - 美国DC③ | 联通| 直连
[2021-10-18 22:23:18,102][INFO][4447903232][config_parser.py:152]netflix - 66云CN2GIA | 三网| 直连
[2021-10-18 22:23:18,103][INFO][4447903232][config_parser.py:152]netflix - 韩国|kr①
[2021-10-18 22:23:18,103][INFO][4447903232][config_parser.py:152]netflix - 韩国|kr②
[2021-10-18 22:23:18,103][INFO][4447903232][config_parser.py:152]netflix - 韩国|kr③
[2021-10-18 22:23:18,103][INFO][4447903232][config_parser.py:152]netflix - HongKong01
[2021-10-18 22:23:18,103][INFO][4447903232][config_parser.py:152]netflix - HongKong02
[2021-10-18 22:23:18,104][INFO][4447903232][ssrspeed_core.py:165]23 node(s) will be test.
[2021-10-18 22:23:18,105][INFO][4447903232][speed_test.py:421]Test mode : speed and tcp ping.Test method : FAST.
[2021-10-18 22:23:18,110][INFO][4447903232][speed_test.py:242]Starting test netflix - 香港 [1/23]
[2021-10-18 22:23:18,115][INFO][4447903232][client_shadowsocks.py:36]Starting Shadowsocks-libev with server azro.xiaofeng01.ml:14002
[2021-10-18 22:23:19,118][INFO][4447903232][speed_test.py:276]Client started.
[2021-10-18 22:23:20,122][INFO][4447903232][geo_ip.py:46]Translating azro.xiaofeng01.ml to ipv4.
[2021-10-18 22:23:20,126][INFO][4447903232][geo_ip.py:63]Starting Geo IP.
[2021-10-18 22:23:21,304][INFO][4447903232][speed_test.py:111]Node inbound IP : 198.18.2.214, Geo : N/A Unknown City, N/A
[2021-10-18 22:23:21,304][INFO][4447903232][speed_test_methods.py:72]Testing latency to server.
[2021-10-18 22:23:22,413][INFO][4447903232][speed_test_methods.py:68]Testing latency to google.
[2021-10-18 22:23:25,409][INFO][4447903232][geo_ip.py:63]Starting Geo IP.
[2021-10-18 22:23:26,532][INFO][4447903232][speed_test.py:127]Node outbound IP : 207.46.146.101, Geo : Hong Kong Central, Microsoft Azure
[2021-10-18 22:23:26,532][INFO][4447903232][speed_test.py:135]Performing netflix test LOCAL_PORT: 1087.
[2021-10-18 22:23:29,570][INFO][4447903232][speed_test.py:153]Netflix IP : 207.46.146.101
[2021-10-18 22:23:31,182][INFO][4447903232][speed_test.py:167]Netflix test result: 仅自制剧.
[2021-10-18 22:23:31,182][INFO][4447903232][speed_test.py:218]Performing UDP NAT Type Test
[2021-10-18 22:23:33,799][INFO][4447903232][speed_test_methods.py:44]Starting speed test with FAST
[2021-10-18 22:23:33,800][WARNING][4447903232][speed_test.py:374]Re-testing node.
[2021-10-18 22:23:33,800][INFO][4447903232][speed_test_methods.py:44]Starting speed test with FAST
[2021-10-18 22:23:34,803][INFO][4447903232][speed_test.py:242]Starting test netflix - 香港02 [2/23]
[2021-10-18 22:23:34,811][INFO][4447903232][client_shadowsocks.py:36]Starting Shadowsocks-libev with server azro1.xiaofeng01.ml:14002
[2021-10-18 22:23:35,818][INFO][4447903232][speed_test.py:276]Client started.
[2021-10-18 22:23:36,828][INFO][4447903232][geo_ip.py:46]Translating azro1.xiaofeng01.ml to ipv4.
[2021-10-18 22:23:36,831][INFO][4447903232][geo_ip.py:63]Starting Geo IP.
[2021-10-18 22:23:38,958][INFO][4447903232][speed_test.py:111]Node inbound IP : 198.18.2.220, Geo : N/A Unknown City, N/A
[2021-10-18 22:23:38,958][INFO][4447903232][speed_test_methods.py:72]Testing latency to server.
[2021-10-18 22:23:40,040][INFO][4447903232][speed_test_methods.py:68]Testing latency to google.
[2021-10-18 22:23:41,566][INFO][4447903232][geo_ip.py:63]Starting Geo IP.
[2021-10-18 22:23:43,976][INFO][4447903232][speed_test.py:127]Node outbound IP : 23.101.8.217, Geo : Hong Kong Central, Microsoft Azure
[2021-10-18 22:23:43,977][INFO][4447903232][speed_test.py:135]Performing netflix test LOCAL_PORT: 1087.
[2021-10-18 22:23:47,326][INFO][4447903232][speed_test.py:153]Netflix IP : 23.101.8.217
[2021-10-18 22:23:48,666][INFO][4447903232][speed_test.py:167]Netflix test result: 仅自制剧.
[2021-10-18 22:23:48,667][INFO][4447903232][speed_test.py:218]Performing UDP NAT Type Test
[2021-10-18 22:23:49,997][INFO][4447903232][speed_test_methods.py:44]Starting speed test with FAST
[2021-10-18 22:23:49,997][WARNING][4447903232][speed_test.py:374]Re-testing node.
[2021-10-18 22:23:49,998][INFO][4447903232][speed_test_methods.py:44]Starting speed test with FAST
[2021-10-18 22:23:51,000][INFO][4447903232][speed_test.py:242]Starting test netflix - 美国加利福利亚|中转|枣庄 [3/23]
[2021-10-18 22:23:51,008][INFO][4447903232][client_shadowsocks.py:36]Starting Shadowsocks-libev with server 119.188.241.223:40058
[2021-10-18 22:23:52,013][INFO][4447903232][speed_test.py:276]Client started.
[2021-10-18 22:23:53,020][INFO][4447903232][geo_ip.py:46]Translating 119.188.241.223 to ipv4.
[2021-10-18 22:23:53,020][INFO][4447903232][geo_ip.py:63]Starting Geo IP.
[2021-10-18 22:23:54,623][INFO][4447903232][speed_test.py:111]Node inbound IP : 119.188.241.223, Geo : China Shenzhen, China Unicom Liaoning
[2021-10-18 22:23:54,624][INFO][4447903232][speed_test_methods.py:72]Testing latency to server.
[2021-10-18 22:23:55,701][INFO][4447903232][speed_test_methods.py:68]Testing latency to google.
[2021-10-18 22:24:04,272][INFO][4447903232][geo_ip.py:63]Starting Geo IP.
[2021-10-18 22:24:05,993][INFO][4447903232][speed_test.py:127]Node outbound IP : 167.160.189.197, Geo : United States Los Angeles, QuadraNet
[2021-10-18 22:24:05,993][INFO][4447903232][speed_test.py:135]Performing netflix test LOCAL_PORT: 1087.
[2021-10-18 22:24:10,608][INFO][4447903232][speed_test.py:153]Netflix IP : 8.26.182.79
[2021-10-18 22:24:13,292][INFO][4447903232][speed_test.py:173]Netflix test result: DNS解锁.
[2021-10-18 22:24:13,293][INFO][4447903232][speed_test.py:218]Performing UDP NAT Type Test
[2021-10-18 22:24:16,312][INFO][4447903232][speed_test_methods.py:44]Starting speed test with FAST
[2021-10-18 22:24:16,312][WARNING][4447903232][speed_test.py:374]Re-testing node.
[2021-10-18 22:24:16,313][INFO][4447903232][speed_test_methods.py:44]Starting speed test with FAST
[2021-10-18 22:24:17,316][INFO][4447903232][speed_test.py:242]Starting test netflix - TripodCloud CN2GIA | 三网| 中转 [4/23]
[2021-10-18 22:24:17,326][INFO][4447903232][client_shadowsocks.py:36]Starting Shadowsocks-libev with server 119.188.241.223:21003
[2021-10-18 22:24:18,333][INFO][4447903232][speed_test.py:276]Client started.
[2021-10-18 22:24:19,342][INFO][4447903232][geo_ip.py:46]Translating 119.188.241.223 to ipv4.
[2021-10-18 22:24:19,343][INFO][4447903232][geo_ip.py:63]Starting Geo IP.
[2021-10-18 22:24:21,045][INFO][4447903232][speed_test.py:111]Node inbound IP : 119.188.241.223, Geo : China Shenzhen, China Unicom Liaoning
[2021-10-18 22:24:21,046][INFO][4447903232][speed_test_methods.py:72]Testing latency to server.
[2021-10-18 22:24:22,125][INFO][4447903232][speed_test_methods.py:68]Testing latency to google.
[2021-10-18 22:24:29,238][INFO][4447903232][geo_ip.py:63]Starting Geo IP.
[2021-10-18 22:24:30,603][INFO][4447903232][speed_test.py:127]Node outbound IP : 107.148.248.110, Geo : China Hangzhou, Peg Tech
[2021-10-18 22:24:30,604][INFO][4447903232][speed_test.py:135]Performing netflix test LOCAL_PORT: 1087.
[2021-10-18 22:24:33,542][INFO][4447903232][speed_test.py:153]Netflix IP : 107.148.248.110
[2021-10-18 22:24:34,977][INFO][4447903232][speed_test.py:167]Netflix test result: 仅自制剧.
[2021-10-18 22:24:34,978][INFO][4447903232][speed_test.py:218]Performing UDP NAT Type Test
[2021-10-18 22:24:36,559][ERROR][4447903232][speed_test.py:227]
Traceback (most recent call last):
  File "/Users/chinnsenn/Developments.localized/PythonProjects/SSRSpeedN-Mod/ssrspeed/speed_test/speed_test.py", line 219, in __nat_type_test
    t, eip, eport, sip = pynat.get_ip_info(
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/site-packages/pynat.py", line 238, in get_ip_info
    source_ip = get_internal_ip(stun_addr)
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/site-packages/pynat.py", line 163, in get_internal_ip
    sock.connect(test_addr)
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
[2021-10-18 22:24:36,565][INFO][4447903232][speed_test_methods.py:44]Starting speed test with FAST
[2021-10-18 22:24:36,566][WARNING][4447903232][speed_test.py:374]Re-testing node.
[2021-10-18 22:24:36,566][INFO][4447903232][speed_test_methods.py:44]Starting speed test with FAST
[2021-10-18 22:24:37,570][INFO][4447903232][speed_test.py:242]Starting test netflix - 西伯利亚 | 中转|枣庄 [5/23]
[2021-10-18 22:24:37,578][INFO][4447903232][client_shadowsocks.py:36]Starting Shadowsocks-libev with server 119.188.241.223:21007
[2021-10-18 22:24:38,584][INFO][4447903232][speed_test.py:276]Client started.
[2021-10-18 22:24:39,591][INFO][4447903232][geo_ip.py:46]Translating 119.188.241.223 to ipv4.
[2021-10-18 22:24:39,592][INFO][4447903232][geo_ip.py:63]Starting Geo IP.
[2021-10-18 22:24:41,792][INFO][4447903232][speed_test.py:111]Node inbound IP : 119.188.241.223, Geo : China Shenzhen, China Unicom Liaoning
[2021-10-18 22:24:41,793][INFO][4447903232][speed_test_methods.py:72]Testing latency to server.
[2021-10-18 22:24:42,889][INFO][4447903232][speed_test_methods.py:68]Testing latency to google.
[2021-10-18 22:24:50,673][WARNING][4447903232][ping.py:71]Google Ping Timeout 1 times.
[2021-10-18 22:24:53,678][WARNING][4447903232][ping.py:71]Google Ping Timeout 2 times.
[2021-10-18 22:24:58,216][INFO][4447903232][geo_ip.py:63]Starting Geo IP.
[2021-10-18 22:24:59,438][INFO][4447903232][speed_test.py:127]Node outbound IP : 194.5.78.128, Geo : Russia Unknown City, LLC Baxet
[2021-10-18 22:24:59,438][INFO][4447903232][speed_test.py:135]Performing netflix test LOCAL_PORT: 1087.
[2021-10-18 22:25:02,790][INFO][4447903232][speed_test.py:153]Netflix IP : 8.41.37.149
[2021-10-18 22:25:05,915][INFO][4447903232][speed_test.py:173]Netflix test result: DNS解锁.
[2021-10-18 22:25:05,916][INFO][4447903232][speed_test.py:218]Performing UDP NAT Type Test
[2021-10-18 22:25:16,143][INFO][4447903232][speed_test_methods.py:44]Starting speed test with FAST
[2021-10-18 22:25:16,144][WARNING][4447903232][speed_test.py:374]Re-testing node.
[2021-10-18 22:25:16,144][INFO][4447903232][speed_test_methods.py:44]Starting speed test with FAST
[2021-10-18 22:25:17,150][INFO][4447903232][speed_test.py:242]Starting test netflix - 南非-ss | 三网 |中转枣庄 [6/23]
[2021-10-18 22:25:17,160][INFO][4447903232][client_shadowsocks.py:36]Starting Shadowsocks-libev with server 119.188.241.223:21005
[2021-10-18 22:25:18,167][INFO][4447903232][speed_test.py:276]Client started.
[2021-10-18 22:25:19,176][INFO][4447903232][geo_ip.py:46]Translating 119.188.241.223 to ipv4.
[2021-10-18 22:25:19,177][INFO][4447903232][geo_ip.py:63]Starting Geo IP.
[2021-10-18 22:25:21,730][INFO][4447903232][speed_test.py:111]Node inbound IP : 119.188.241.223, Geo : China Shenzhen, China Unicom Liaoning
[2021-10-18 22:25:21,730][INFO][4447903232][speed_test_methods.py:72]Testing latency to server.
[2021-10-18 22:25:22,830][INFO][4447903232][speed_test_methods.py:68]Testing latency to google.
[2021-10-18 22:25:39,246][INFO][4447903232][geo_ip.py:63]Starting Geo IP.
[2021-10-18 22:25:41,022][INFO][4447903232][speed_test.py:127]Node outbound IP : 193.239.178.177, Geo : United Kingdom Unknown City, JUSTG
[2021-10-18 22:25:41,023][INFO][4447903232][speed_test.py:135]Performing netflix test LOCAL_PORT: 1087.
[2021-10-18 22:25:44,468][INFO][4447903232][speed_test.py:153]Netflix IP : 193.239.178.177
[2021-10-18 22:25:48,294][INFO][4447903232][speed_test.py:170]Netflix test result: 原生解锁.
[2021-10-18 22:25:48,294][INFO][4447903232][speed_test.py:218]Performing UDP NAT Type Test
[2021-10-18 22:25:51,347][INFO][4447903232][speed_test_methods.py:44]Starting speed test with FAST
[2021-10-18 22:25:51,348][WARNING][4447903232][speed_test.py:374]Re-testing node.
[2021-10-18 22:25:51,348][INFO][4447903232][speed_test_methods.py:44]Starting speed test with FAST
[2021-10-18 22:25:52,353][INFO][4447903232][speed_test.py:242]Starting test netflix - 美国圣何塞①  | 中转 |枣庄 [7/23]
[2021-10-18 22:25:52,363][INFO][4447903232][client_shadowsocks.py:36]Starting Shadowsocks-libev with server 119.188.241.223:21002
[2021-10-18 22:25:53,370][INFO][4447903232][speed_test.py:276]Client started.
[2021-10-18 22:25:54,375][INFO][4447903232][geo_ip.py:46]Translating 119.188.241.223 to ipv4.
[2021-10-18 22:25:54,376][INFO][4447903232][geo_ip.py:63]Starting Geo IP.
[2021-10-18 22:25:56,701][INFO][4447903232][speed_test.py:111]Node inbound IP : 119.188.241.223, Geo : China Shenzhen, China Unicom Liaoning
[2021-10-18 22:25:56,702][INFO][4447903232][speed_test_methods.py:72]Testing latency to server.
[2021-10-18 22:25:57,801][INFO][4447903232][speed_test_methods.py:68]Testing latency to google.
[2021-10-18 22:26:03,403][WARNING][4447903232][ping.py:71]Google Ping Timeout 1 times.
[2021-10-18 22:26:12,339][WARNING][4447903232][ping.py:71]Google Ping Timeout 2 times.
[2021-10-18 22:26:12,340][INFO][4447903232][geo_ip.py:63]Starting Geo IP.
[2021-10-18 22:27:00,787][ERROR][4447903232][geo_ip.py:73]Geo IP Timeout.
[2021-10-18 22:27:00,787][INFO][4447903232][speed_test.py:127]Node outbound IP : N/A, Geo : N/A Unknown City, N/A
[2021-10-18 22:27:00,787][INFO][4447903232][speed_test.py:135]Performing netflix test LOCAL_PORT: 1087.
[2021-10-18 22:27:04,557][INFO][4447903232][speed_test.py:153]Netflix IP : 23.234.244.157
[2021-10-18 22:27:06,512][INFO][4447903232][speed_test.py:167]Netflix test result: 仅自制剧.
[2021-10-18 22:27:06,513][INFO][4447903232][speed_test.py:218]Performing UDP NAT Type Test
[2021-10-18 22:27:10,803][INFO][4447903232][speed_test_methods.py:44]Starting speed test with FAST
[2021-10-18 22:27:10,803][WARNING][4447903232][speed_test.py:374]Re-testing node.
[2021-10-18 22:27:10,804][INFO][4447903232][speed_test_methods.py:44]Starting speed test with FAST
[2021-10-18 22:27:11,808][INFO][4447903232][speed_test.py:242]Starting test netflix - 美国洛杉矶② |枣庄中转 [8/23]
[2021-10-18 22:27:11,816][INFO][4447903232][client_shadowsocks.py:36]Starting Shadowsocks-libev with server 119.188.241.223:21001
[2021-10-18 22:27:12,822][INFO][4447903232][speed_test.py:276]Client started.
[2021-10-18 22:27:13,829][INFO][4447903232][geo_ip.py:46]Translating 119.188.241.223 to ipv4.
[2021-10-18 22:27:13,830][INFO][4447903232][geo_ip.py:63]Starting Geo IP.
[2021-10-18 22:27:18,698][INFO][4447903232][speed_test.py:111]Node inbound IP : 119.188.241.223, Geo : China Shenzhen, China Unicom Liaoning
[2021-10-18 22:27:18,699][INFO][4447903232][speed_test_methods.py:72]Testing latency to server.
[2021-10-18 22:27:22,929][INFO][4447903232][speed_test_methods.py:68]Testing latency to google.
[2021-10-18 22:27:25,939][WARNING][4447903232][ping.py:71]Google Ping Timeout 1 times.
[2021-10-18 22:27:29,805][WARNING][4447903232][ping.py:71]Google Ping Timeout 2 times.
[2021-10-18 22:27:33,664][WARNING][4447903232][ping.py:71]Google Ping Timeout 3 times.
[2021-10-18 22:27:33,668][INFO][4447903232][geo_ip.py:63]Starting Geo IP.
[2021-10-18 22:27:37,690][INFO][4447903232][speed_test.py:127]Node outbound IP : 72.44.74.125, Geo : United States Unknown City, Multacom Corporation
[2021-10-18 22:27:37,691][INFO][4447903232][speed_test.py:135]Performing netflix test LOCAL_PORT: 1087.
[2021-10-18 22:27:40,604][INFO][4447903232][speed_test.py:153]Netflix IP : 72.44.74.125
[2021-10-18 22:27:44,944][INFO][4447903232][speed_test.py:167]Netflix test result: 仅自制剧.
[2021-10-18 22:27:44,944][INFO][4447903232][speed_test.py:218]Performing UDP NAT Type Test
[2021-10-18 22:27:46,492][INFO][4447903232][speed_test_methods.py:44]Starting speed test with FAST
[2021-10-18 22:27:46,492][WARNING][4447903232][speed_test.py:374]Re-testing node.
[2021-10-18 22:27:46,492][INFO][4447903232][speed_test_methods.py:44]Starting speed test with FAST
[2021-10-18 22:27:47,497][INFO][4447903232][speed_test.py:242]Starting test netflix - 美国洛杉矶③  | 枣庄中转 [9/23]
[2021-10-18 22:27:47,507][INFO][4447903232][client_shadowsocks.py:36]Starting Shadowsocks-libev with server 119.188.241.223:21006
[2021-10-18 22:27:48,515][INFO][4447903232][speed_test.py:276]Client started.
[2021-10-18 22:27:49,522][INFO][4447903232][geo_ip.py:46]Translating 119.188.241.223 to ipv4.
[2021-10-18 22:27:49,522][INFO][4447903232][geo_ip.py:63]Starting Geo IP.
[2021-10-18 22:27:51,325][INFO][4447903232][speed_test.py:111]Node inbound IP : 119.188.241.223, Geo : China Shenzhen, China Unicom Liaoning
[2021-10-18 22:27:51,325][INFO][4447903232][speed_test_methods.py:72]Testing latency to server.
[2021-10-18 22:27:52,498][INFO][4447903232][speed_test_methods.py:68]Testing latency to google.
[2021-10-18 22:28:03,654][INFO][4447903232][geo_ip.py:63]Starting Geo IP.
[2021-10-18 22:28:06,440][INFO][4447903232][speed_test.py:127]Node outbound IP : 107.175.134.188, Geo : United States Ashburn, ColoCrossing
[2021-10-18 22:28:06,440][INFO][4447903232][speed_test.py:135]Performing netflix test LOCAL_PORT: 1087.
[2021-10-18 22:28:09,828][INFO][4447903232][speed_test.py:153]Netflix IP : 107.175.134.188
[2021-10-18 22:28:12,716][INFO][4447903232][speed_test.py:167]Netflix test result: 仅自制剧.
[2021-10-18 22:28:12,717][INFO][4447903232][speed_test.py:218]Performing UDP NAT Type Test
[2021-10-18 22:28:15,347][INFO][4447903232][speed_test_methods.py:44]Starting speed test with FAST
[2021-10-18 22:28:15,348][WARNING][4447903232][speed_test.py:374]Re-testing node.
[2021-10-18 22:28:15,348][INFO][4447903232][speed_test_methods.py:44]Starting speed test with FAST
[2021-10-18 22:28:16,354][INFO][4447903232][speed_test.py:242]Starting test netflix - 南非-ss | 三网 |解锁奈飞| 直连 [10/23]
[2021-10-18 22:28:16,365][INFO][4447903232][client_shadowsocks.py:36]Starting Shadowsocks-libev with server ff.xiaofeng01.ml:11404
[2021-10-18 22:28:17,372][INFO][4447903232][speed_test.py:276]Client started.
[2021-10-18 22:28:18,381][INFO][4447903232][geo_ip.py:46]Translating ff.xiaofeng01.ml to ipv4.
[2021-10-18 22:28:18,382][INFO][4447903232][geo_ip.py:63]Starting Geo IP.
[2021-10-18 22:28:23,422][ERROR][4447903232][geo_ip.py:73]Geo IP Timeout.
[2021-10-18 22:28:23,422][INFO][4447903232][speed_test.py:111]Node inbound IP : 198.18.3.66, Geo : N/A Unknown City, N/A
[2021-10-18 22:28:23,423][INFO][4447903232][speed_test_methods.py:72]Testing latency to server.
[2021-10-18 22:28:24,497][INFO][4447903232][speed_test_methods.py:68]Testing latency to google.
[2021-10-18 22:28:27,502][WARNING][4447903232][ping.py:71]Google Ping Timeout 1 times.
[2021-10-18 22:28:30,507][WARNING][4447903232][ping.py:71]Google Ping Timeout 2 times.
[2021-10-18 22:28:33,513][WARNING][4447903232][ping.py:71]Google Ping Timeout 3 times.
[2021-10-18 22:28:33,514][INFO][4447903232][geo_ip.py:63]Starting Geo IP.
[2021-10-18 22:28:38,552][ERROR][4447903232][geo_ip.py:73]Geo IP Timeout.
[2021-10-18 22:28:38,553][INFO][4447903232][speed_test.py:127]Node outbound IP : N/A, Geo : N/A Unknown City, N/A
[2021-10-18 22:28:38,554][INFO][4447903232][speed_test.py:135]Performing netflix test LOCAL_PORT: 1087.
[2021-10-18 22:28:43,621][ERROR][4447903232][speed_test.py:177]代理服务器连接异常：(MaxRetryError("SOCKSHTTPSConnectionPool(host='www.netflix.com', port=443): Max retries exceeded with url: /title/70242311 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))"),)
[2021-10-18 22:28:44,628][INFO][4447903232][speed_test.py:242]Starting test netflix - 香港vm①ss | 三网 | 解锁奈飞| 直连 [11/23]
[2021-10-18 22:28:44,638][INFO][4447903232][client_shadowsocks.py:36]Starting Shadowsocks-libev with server vmshell.xiaofeng.us:10700
[2021-10-18 22:28:45,643][INFO][4447903232][speed_test.py:276]Client started.
[2021-10-18 22:28:46,651][INFO][4447903232][geo_ip.py:46]Translating vmshell.xiaofeng.us to ipv4.
[2021-10-18 22:28:46,654][INFO][4447903232][geo_ip.py:63]Starting Geo IP.
[2021-10-18 22:28:48,654][INFO][4447903232][speed_test.py:111]Node inbound IP : 198.18.2.213, Geo : N/A Unknown City, N/A
[2021-10-18 22:28:48,654][INFO][4447903232][speed_test_methods.py:72]Testing latency to server.
[2021-10-18 22:28:49,721][INFO][4447903232][speed_test_methods.py:68]Testing latency to google.
[2021-10-18 22:28:56,870][INFO][4447903232][geo_ip.py:63]Starting Geo IP.
[2021-10-18 22:28:58,839][INFO][4447903232][speed_test.py:127]Node outbound IP : 150.129.218.23, Geo : China Unknown City, Cnservers LLC
[2021-10-18 22:28:58,839][INFO][4447903232][speed_test.py:135]Performing netflix test LOCAL_PORT: 1087.
[2021-10-18 22:29:02,442][INFO][4447903232][speed_test.py:153]Netflix IP : 150.129.218.23
[2021-10-18 22:29:06,088][INFO][4447903232][speed_test.py:170]Netflix test result: 原生解锁.
[2021-10-18 22:29:06,089][INFO][4447903232][speed_test.py:218]Performing UDP NAT Type Test
[2021-10-18 22:29:08,466][INFO][4447903232][speed_test_methods.py:44]Starting speed test with FAST
[2021-10-18 22:29:08,467][WARNING][4447903232][speed_test.py:374]Re-testing node.
[2021-10-18 22:29:08,467][INFO][4447903232][speed_test_methods.py:44]Starting speed test with FAST
[2021-10-18 22:29:09,468][INFO][4447903232][speed_test.py:242]Starting test netflix - 香港vm②V2 | 三网 | 解锁奈飞| 直连 [12/23]
[2021-10-18 22:29:09,478][INFO][4447903232][client_v2ray.py:36]Starting v2ray-core with server vmshell.xiaofeng.us:443
[2021-10-18 22:29:10,481][INFO][4447903232][speed_test.py:276]Client started.
[2021-10-18 22:29:11,486][INFO][4447903232][geo_ip.py:46]Translating vmshell.xiaofeng.us to ipv4.
[2021-10-18 22:29:11,511][INFO][4447903232][geo_ip.py:63]Starting Geo IP.
[2021-10-18 22:29:14,346][INFO][4447903232][speed_test.py:111]Node inbound IP : 198.18.2.213, Geo : N/A Unknown City, N/A
[2021-10-18 22:29:14,346][INFO][4447903232][speed_test_methods.py:72]Testing latency to server.
[2021-10-18 22:29:15,421][INFO][4447903232][speed_test_methods.py:68]Testing latency to google.
[2021-10-18 22:29:19,249][INFO][4447903232][geo_ip.py:63]Starting Geo IP.
[2021-10-18 22:29:20,980][INFO][4447903232][speed_test.py:127]Node outbound IP : 150.129.218.23, Geo : China Unknown City, Cnservers LLC
[2021-10-18 22:29:20,980][INFO][4447903232][speed_test.py:135]Performing netflix test LOCAL_PORT: 1087.
[2021-10-18 22:29:24,404][INFO][4447903232][speed_test.py:153]Netflix IP : 150.129.218.23
[2021-10-18 22:29:27,291][INFO][4447903232][speed_test.py:170]Netflix test result: 原生解锁.
[2021-10-18 22:29:27,291][INFO][4447903232][speed_test.py:218]Performing UDP NAT Type Test
[2021-10-18 22:29:28,400][ERROR][4447903232][speed_test.py:227]
Traceback (most recent call last):
  File "/Users/chinnsenn/Developments.localized/PythonProjects/SSRSpeedN-Mod/ssrspeed/speed_test/speed_test.py", line 219, in __nat_type_test
    t, eip, eport, sip = pynat.get_ip_info(
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/site-packages/pynat.py", line 224, in get_ip_info
    stun_addr = find_stun_server(sock)
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/site-packages/pynat.py", line 190, in find_stun_server
    response = get_stun_response(sock, stun_addr, max_timeouts=1)
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/site-packages/pynat.py", line 106, in get_stun_response
    trans_id = send_stun_message(sock, addr, BIND_REQUEST_MSG, trans_id, send_data)
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/site-packages/pynat.py", line 94, in send_stun_message
    sock.sendto(data, addr)
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/site-packages/socks.py", line 377, in sendto
    self._write_SOCKS5_address(address, header)
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/site-packages/socks.py", line 558, in _write_SOCKS5_address
    addr_bytes = socket.inet_pton(family, host)
TypeError: inet_pton() argument 2 must be str, not bytes
[2021-10-18 22:29:28,405][INFO][4447903232][speed_test_methods.py:44]Starting speed test with FAST
[2021-10-18 22:29:28,406][WARNING][4447903232][speed_test.py:374]Re-testing node.
[2021-10-18 22:29:28,406][INFO][4447903232][speed_test_methods.py:44]Starting speed test with FAST
[2021-10-18 22:29:29,411][INFO][4447903232][speed_test.py:242]Starting test netflix - 西伯利亚 | 解锁奈飞| 直连 [13/23]
[2021-10-18 22:29:29,423][INFO][4447903232][client_shadowsocks.py:36]Starting Shadowsocks-libev with server lmz.xiaofeng01.ga:11405
[2021-10-18 22:29:30,430][INFO][4447903232][speed_test.py:276]Client started.
[2021-10-18 22:29:31,441][INFO][4447903232][geo_ip.py:46]Translating lmz.xiaofeng01.ga to ipv4.
[2021-10-18 22:29:31,444][INFO][4447903232][geo_ip.py:63]Starting Geo IP.
[2021-10-18 22:29:32,585][INFO][4447903232][speed_test.py:111]Node inbound IP : 198.18.3.67, Geo : N/A Unknown City, N/A
[2021-10-18 22:29:32,585][INFO][4447903232][speed_test_methods.py:72]Testing latency to server.
[2021-10-18 22:29:33,667][INFO][4447903232][speed_test_methods.py:68]Testing latency to google.
[2021-10-18 22:29:40,360][INFO][4447903232][geo_ip.py:63]Starting Geo IP.
[2021-10-18 22:29:41,346][INFO][4447903232][speed_test.py:127]Node outbound IP : 194.5.78.128, Geo : Russia Unknown City, LLC Baxet
[2021-10-18 22:29:41,347][INFO][4447903232][speed_test.py:135]Performing netflix test LOCAL_PORT: 1087.
[2021-10-18 22:29:44,016][INFO][4447903232][speed_test.py:153]Netflix IP : 8.41.37.149
[2021-10-18 22:29:47,098][INFO][4447903232][speed_test.py:173]Netflix test result: DNS解锁.
[2021-10-18 22:29:47,099][INFO][4447903232][speed_test.py:218]Performing UDP NAT Type Test
[2021-10-18 22:29:50,126][INFO][4447903232][speed_test_methods.py:44]Starting speed test with FAST
[2021-10-18 22:29:50,127][WARNING][4447903232][speed_test.py:374]Re-testing node.
[2021-10-18 22:29:50,128][INFO][4447903232][speed_test_methods.py:44]Starting speed test with FAST
[2021-10-18 22:29:51,130][INFO][4447903232][speed_test.py:242]Starting test netflix - TripodCloud CN2GIA | 三网| 直连 [14/23]
[2021-10-18 22:29:51,142][INFO][4447903232][client_shadowsocks.py:36]Starting Shadowsocks-libev with server tro.xiaofeng01.ml:15103
[2021-10-18 22:29:52,148][INFO][4447903232][speed_test.py:276]Client started.
[2021-10-18 22:29:53,155][INFO][4447903232][geo_ip.py:46]Translating tro.xiaofeng01.ml to ipv4.
[2021-10-18 22:29:53,157][INFO][4447903232][geo_ip.py:63]Starting Geo IP.
[2021-10-18 22:29:54,352][INFO][4447903232][speed_test.py:111]Node inbound IP : 198.18.3.70, Geo : N/A Unknown City, N/A
[2021-10-18 22:29:54,352][INFO][4447903232][speed_test_methods.py:72]Testing latency to server.
[2021-10-18 22:29:55,430][INFO][4447903232][speed_test_methods.py:68]Testing latency to google.
[2021-10-18 22:29:59,328][INFO][4447903232][geo_ip.py:63]Starting Geo IP.
[2021-10-18 22:30:00,590][INFO][4447903232][speed_test.py:127]Node outbound IP : 107.148.248.110, Geo : China Hangzhou, Peg Tech
[2021-10-18 22:30:00,590][INFO][4447903232][speed_test.py:135]Performing netflix test LOCAL_PORT: 1087.
[2021-10-18 22:30:02,128][INFO][4447903232][speed_test.py:153]Netflix IP : 107.148.248.110
[2021-10-18 22:30:03,089][INFO][4447903232][speed_test.py:167]Netflix test result: 仅自制剧.
[2021-10-18 22:30:03,090][INFO][4447903232][speed_test.py:218]Performing UDP NAT Type Test
[2021-10-18 22:30:04,635][INFO][4447903232][speed_test_methods.py:44]Starting speed test with FAST
[2021-10-18 22:30:04,636][WARNING][4447903232][speed_test.py:374]Re-testing node.
[2021-10-18 22:30:04,637][INFO][4447903232][speed_test_methods.py:44]Starting speed test with FAST
[2021-10-18 22:30:05,639][INFO][4447903232][speed_test.py:242]Starting test netflix - 美国圣何塞① | 联通| 直连 [15/23]
[2021-10-18 22:30:05,649][INFO][4447903232][client_shadowsocks.py:36]Starting Shadowsocks-libev with server lq01.ml:11402
[2021-10-18 22:30:06,655][INFO][4447903232][speed_test.py:276]Client started.
[2021-10-18 22:30:07,660][INFO][4447903232][geo_ip.py:46]Translating lq01.ml to ipv4.
[2021-10-18 22:30:07,662][INFO][4447903232][geo_ip.py:63]Starting Geo IP.
[2021-10-18 22:30:10,119][INFO][4447903232][speed_test.py:111]Node inbound IP : 198.18.3.20, Geo : N/A Unknown City, N/A
[2021-10-18 22:30:10,119][INFO][4447903232][speed_test_methods.py:72]Testing latency to server.
[2021-10-18 22:30:11,219][INFO][4447903232][speed_test_methods.py:68]Testing latency to google.
[2021-10-18 22:30:21,765][INFO][4447903232][geo_ip.py:63]Starting Geo IP.
[2021-10-18 22:30:23,252][INFO][4447903232][speed_test.py:127]Node outbound IP : 23.234.244.157, Geo : United States Unknown City, Multacom Corporation
[2021-10-18 22:30:23,252][INFO][4447903232][speed_test.py:135]Performing netflix test LOCAL_PORT: 1087.
[2021-10-18 22:30:25,945][INFO][4447903232][speed_test.py:153]Netflix IP : 23.234.244.157
[2021-10-18 22:30:34,993][INFO][4447903232][speed_test.py:167]Netflix test result: 仅自制剧.
[2021-10-18 22:30:34,994][INFO][4447903232][speed_test.py:218]Performing UDP NAT Type Test
[2021-10-18 22:30:36,358][INFO][4447903232][speed_test_methods.py:44]Starting speed test with FAST
[2021-10-18 22:30:36,359][WARNING][4447903232][speed_test.py:374]Re-testing node.
[2021-10-18 22:30:36,359][INFO][4447903232][speed_test_methods.py:44]Starting speed test with FAST
[2021-10-18 22:30:37,364][INFO][4447903232][speed_test.py:242]Starting test netflix - 美国洛杉矶② | 联通| 直连 [16/23]
[2021-10-18 22:30:37,374][INFO][4447903232][client_shadowsocks.py:36]Starting Shadowsocks-libev with server jiedian.xxcr.tk:11300
[2021-10-18 22:30:38,381][INFO][4447903232][speed_test.py:276]Client started.
[2021-10-18 22:30:39,388][INFO][4447903232][geo_ip.py:46]Translating jiedian.xxcr.tk to ipv4.
[2021-10-18 22:30:39,390][INFO][4447903232][geo_ip.py:63]Starting Geo IP.
[2021-10-18 22:30:41,620][INFO][4447903232][speed_test.py:111]Node inbound IP : 198.18.3.21, Geo : N/A Unknown City, N/A
[2021-10-18 22:30:41,621][INFO][4447903232][speed_test_methods.py:72]Testing latency to server.
[2021-10-18 22:30:42,709][INFO][4447903232][speed_test_methods.py:68]Testing latency to google.
[2021-10-18 22:30:46,759][WARNING][4447903232][ping.py:71]Google Ping Timeout 1 times.
[2021-10-18 22:30:52,662][INFO][4447903232][geo_ip.py:63]Starting Geo IP.
[2021-10-18 22:30:53,946][INFO][4447903232][speed_test.py:127]Node outbound IP : 72.44.74.125, Geo : United States Unknown City, Multacom Corporation
[2021-10-18 22:30:53,947][INFO][4447903232][speed_test.py:135]Performing netflix test LOCAL_PORT: 1087.
[2021-10-18 22:31:06,206][INFO][4447903232][speed_test.py:153]Netflix IP : 72.44.74.125
[2021-10-18 22:31:07,724][INFO][4447903232][speed_test.py:167]Netflix test result: 仅自制剧.
[2021-10-18 22:31:07,725][INFO][4447903232][speed_test.py:218]Performing UDP NAT Type Test
[2021-10-18 22:31:10,751][INFO][4447903232][speed_test_methods.py:44]Starting speed test with FAST
[2021-10-18 22:31:10,752][WARNING][4447903232][speed_test.py:374]Re-testing node.
[2021-10-18 22:31:10,753][INFO][4447903232][speed_test_methods.py:44]Starting speed test with FAST
[2021-10-18 22:31:11,759][INFO][4447903232][speed_test.py:242]Starting test netflix - 美国DC③ | 联通| 直连 [17/23]
[2021-10-18 22:31:11,768][INFO][4447903232][client_shadowsocks.py:36]Starting Shadowsocks-libev with server yzf.xiaofeng01.ml:12000
[2021-10-18 22:31:12,771][INFO][4447903232][speed_test.py:276]Client started.
[2021-10-18 22:31:13,777][INFO][4447903232][geo_ip.py:46]Translating yzf.xiaofeng01.ml to ipv4.
[2021-10-18 22:31:13,790][INFO][4447903232][geo_ip.py:63]Starting Geo IP.
[2021-10-18 22:31:15,872][INFO][4447903232][speed_test.py:111]Node inbound IP : 198.18.3.27, Geo : N/A Unknown City, N/A
[2021-10-18 22:31:15,873][INFO][4447903232][speed_test_methods.py:72]Testing latency to server.
[2021-10-18 22:31:16,963][INFO][4447903232][speed_test_methods.py:68]Testing latency to google.
[2021-10-18 22:31:22,812][INFO][4447903232][geo_ip.py:63]Starting Geo IP.
[2021-10-18 22:31:24,918][INFO][4447903232][speed_test.py:127]Node outbound IP : 107.175.134.188, Geo : United States Ashburn, ColoCrossing
[2021-10-18 22:31:24,919][INFO][4447903232][speed_test.py:135]Performing netflix test LOCAL_PORT: 1087.
[2021-10-18 22:31:27,378][INFO][4447903232][speed_test.py:153]Netflix IP : 107.175.134.188
[2021-10-18 22:31:28,707][INFO][4447903232][speed_test.py:167]Netflix test result: 仅自制剧.
[2021-10-18 22:31:28,708][INFO][4447903232][speed_test.py:218]Performing UDP NAT Type Test
[2021-10-18 22:31:30,424][INFO][4447903232][speed_test_methods.py:44]Starting speed test with FAST
[2021-10-18 22:31:30,425][WARNING][4447903232][speed_test.py:374]Re-testing node.
[2021-10-18 22:31:30,426][INFO][4447903232][speed_test_methods.py:44]Starting speed test with FAST
[2021-10-18 22:31:31,433][INFO][4447903232][speed_test.py:242]Starting test netflix - 66云CN2GIA | 三网| 直连 [18/23]
[2021-10-18 22:31:31,444][INFO][4447903232][client_v2ray.py:36]Starting v2ray-core with server cc.xiaofeng01.ml:15101
[2021-10-18 22:31:32,450][INFO][4447903232][speed_test.py:276]Client started.
[2021-10-18 22:31:33,461][INFO][4447903232][geo_ip.py:46]Translating cc.xiaofeng01.ml to ipv4.
[2021-10-18 22:31:33,473][INFO][4447903232][geo_ip.py:63]Starting Geo IP.
[2021-10-18 22:31:38,750][INFO][4447903232][speed_test.py:111]Node inbound IP : 198.18.2.217, Geo : N/A Unknown City, N/A
[2021-10-18 22:31:38,750][INFO][4447903232][speed_test_methods.py:72]Testing latency to server.
[2021-10-18 22:31:39,842][INFO][4447903232][speed_test_methods.py:68]Testing latency to google.
[2021-10-18 22:31:41,739][INFO][4447903232][geo_ip.py:63]Starting Geo IP.
[2021-10-18 22:31:42,641][INFO][4447903232][speed_test.py:127]Node outbound IP : 202.5.30.176, Geo : United States Ashburn, HostUS
[2021-10-18 22:31:42,641][INFO][4447903232][speed_test.py:135]Performing netflix test LOCAL_PORT: 1087.
[2021-10-18 22:31:44,006][INFO][4447903232][speed_test.py:153]Netflix IP : 202.5.30.176
[2021-10-18 22:31:44,794][INFO][4447903232][speed_test.py:167]Netflix test result: 仅自制剧.
[2021-10-18 22:31:44,795][INFO][4447903232][speed_test.py:218]Performing UDP NAT Type Test
[2021-10-18 22:31:46,160][INFO][4447903232][speed_test_methods.py:44]Starting speed test with FAST
[2021-10-18 22:31:46,160][WARNING][4447903232][speed_test.py:374]Re-testing node.
[2021-10-18 22:31:46,160][INFO][4447903232][speed_test_methods.py:44]Starting speed test with FAST
[2021-10-18 22:31:47,165][INFO][4447903232][speed_test.py:242]Starting test netflix - 韩国|kr① [19/23]
[2021-10-18 22:31:47,176][INFO][4447903232][client_shadowsocks.py:36]Starting Shadowsocks-libev with server jgw.xiaofeng01.ml:12003
[2021-10-18 22:31:48,181][INFO][4447903232][speed_test.py:276]Client started.
[2021-10-18 22:31:49,189][INFO][4447903232][geo_ip.py:46]Translating jgw.xiaofeng01.ml to ipv4.
[2021-10-18 22:31:49,191][INFO][4447903232][geo_ip.py:63]Starting Geo IP.
[2021-10-18 22:31:51,242][INFO][4447903232][speed_test.py:111]Node inbound IP : 198.18.2.201, Geo : N/A Unknown City, N/A
[2021-10-18 22:31:51,243][INFO][4447903232][speed_test_methods.py:72]Testing latency to server.
[2021-10-18 22:31:52,315][INFO][4447903232][speed_test_methods.py:68]Testing latency to google.
[2021-10-18 22:32:01,901][INFO][4447903232][geo_ip.py:63]Starting Geo IP.
[2021-10-18 22:32:03,862][INFO][4447903232][speed_test.py:127]Node outbound IP : 140.238.14.125, Geo : South Korea Seoul, Oracle Cloud
[2021-10-18 22:32:03,862][INFO][4447903232][speed_test.py:135]Performing netflix test LOCAL_PORT: 1087.
[2021-10-18 22:32:07,774][INFO][4447903232][speed_test.py:153]Netflix IP : 140.238.14.125
[2021-10-18 22:32:09,026][INFO][4447903232][speed_test.py:167]Netflix test result: 仅自制剧.
[2021-10-18 22:32:09,026][INFO][4447903232][speed_test.py:218]Performing UDP NAT Type Test
[2021-10-18 22:32:12,107][INFO][4447903232][speed_test_methods.py:44]Starting speed test with FAST
[2021-10-18 22:32:12,108][WARNING][4447903232][speed_test.py:374]Re-testing node.
[2021-10-18 22:32:12,108][INFO][4447903232][speed_test_methods.py:44]Starting speed test with FAST
[2021-10-18 22:32:13,113][INFO][4447903232][speed_test.py:242]Starting test netflix - 韩国|kr② [20/23]
[2021-10-18 22:32:13,122][INFO][4447903232][client_shadowsocks.py:36]Starting Shadowsocks-libev with server cms.xxcr.tk:15202
[2021-10-18 22:32:14,127][INFO][4447903232][speed_test.py:276]Client started.
[2021-10-18 22:32:15,136][INFO][4447903232][geo_ip.py:46]Translating cms.xxcr.tk to ipv4.
[2021-10-18 22:32:15,138][INFO][4447903232][geo_ip.py:63]Starting Geo IP.
[2021-10-18 22:32:17,508][INFO][4447903232][speed_test.py:111]Node inbound IP : 198.18.2.196, Geo : N/A Unknown City, N/A
[2021-10-18 22:32:17,509][INFO][4447903232][speed_test_methods.py:72]Testing latency to server.
[2021-10-18 22:32:18,620][INFO][4447903232][speed_test_methods.py:68]Testing latency to google.
[2021-10-18 22:32:23,583][INFO][4447903232][geo_ip.py:63]Starting Geo IP.
[2021-10-18 22:32:25,536][INFO][4447903232][speed_test.py:127]Node outbound IP : 193.123.235.199, Geo : South Korea Seoul, Oracle Cloud
[2021-10-18 22:32:25,537][INFO][4447903232][speed_test.py:135]Performing netflix test LOCAL_PORT: 1087.
[2021-10-18 22:32:30,513][INFO][4447903232][speed_test.py:153]Netflix IP : 193.123.235.199
[2021-10-18 22:32:33,255][INFO][4447903232][speed_test.py:170]Netflix test result: 原生解锁.
[2021-10-18 22:32:33,256][INFO][4447903232][speed_test.py:218]Performing UDP NAT Type Test
[2021-10-18 22:32:36,471][INFO][4447903232][speed_test_methods.py:44]Starting speed test with FAST
[2021-10-18 22:32:36,472][WARNING][4447903232][speed_test.py:374]Re-testing node.
[2021-10-18 22:32:36,472][INFO][4447903232][speed_test_methods.py:44]Starting speed test with FAST
[2021-10-18 22:32:37,478][INFO][4447903232][speed_test.py:242]Starting test netflix - 韩国|kr③ [21/23]
[2021-10-18 22:32:37,485][INFO][4447903232][client_shadowsocks.py:36]Starting Shadowsocks-libev with server arm.freefly.video:12004
[2021-10-18 22:32:38,492][INFO][4447903232][speed_test.py:276]Client started.
[2021-10-18 22:32:39,502][INFO][4447903232][geo_ip.py:46]Translating arm.freefly.video to ipv4.
[2021-10-18 22:32:39,504][INFO][4447903232][geo_ip.py:63]Starting Geo IP.
[2021-10-18 22:32:41,623][INFO][4447903232][speed_test.py:111]Node inbound IP : 198.18.2.239, Geo : N/A Unknown City, N/A
[2021-10-18 22:32:41,624][INFO][4447903232][speed_test_methods.py:72]Testing latency to server.
[2021-10-18 22:32:42,708][INFO][4447903232][speed_test_methods.py:68]Testing latency to google.
[2021-10-18 22:32:48,891][INFO][4447903232][geo_ip.py:63]Starting Geo IP.
[2021-10-18 22:32:50,900][INFO][4447903232][speed_test.py:127]Node outbound IP : 146.56.135.66, Geo : South Korea Seoul, Oracle Cloud
[2021-10-18 22:32:50,901][INFO][4447903232][speed_test.py:135]Performing netflix test LOCAL_PORT: 1087.
[2021-10-18 22:32:55,495][INFO][4447903232][speed_test.py:153]Netflix IP : 146.56.135.66
[2021-10-18 22:32:58,413][INFO][4447903232][speed_test.py:170]Netflix test result: 原生解锁.
[2021-10-18 22:32:58,414][INFO][4447903232][speed_test.py:218]Performing UDP NAT Type Test
[2021-10-18 22:33:01,592][INFO][4447903232][speed_test_methods.py:44]Starting speed test with FAST
[2021-10-18 22:33:01,592][WARNING][4447903232][speed_test.py:374]Re-testing node.
[2021-10-18 22:33:01,593][INFO][4447903232][speed_test_methods.py:44]Starting speed test with FAST
[2021-10-18 22:33:02,597][INFO][4447903232][speed_test.py:242]Starting test netflix - HongKong01 [22/23]
[2021-10-18 22:33:02,603][INFO][4447903232][client_shadowsocks.py:36]Starting Shadowsocks-libev with server aznat1.xiaomai.my03.com:11310
[2021-10-18 22:33:03,608][INFO][4447903232][speed_test.py:276]Client started.
[2021-10-18 22:33:04,617][INFO][4447903232][geo_ip.py:46]Translating aznat1.xiaomai.my03.com to ipv4.
[2021-10-18 22:33:04,619][INFO][4447903232][geo_ip.py:63]Starting Geo IP.
[2021-10-18 22:33:05,786][ERROR][4447903232][geo_ip.py:76]Geo IP Failed.
Traceback (most recent call last):
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/site-packages/urllib3/connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: SOCKSHTTPSConnectionPool(host='api.ip.sb', port=443): Max retries exceeded with url: /geoip/198.18.3.54 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chinnsenn/Developments.localized/PythonProjects/SSRSpeedN-Mod/ssrspeed/utils/geo_ip.py", line 66, in IPLoc
    rep = requests.get("https://api.ip.sb/geoip/{}".format(ip),proxies = {
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: SOCKSHTTPSConnectionPool(host='api.ip.sb', port=443): Max retries exceeded with url: /geoip/198.18.3.54 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))
[2021-10-18 22:33:05,804][INFO][4447903232][speed_test.py:111]Node inbound IP : 198.18.3.54, Geo : N/A Unknown City, N/A
[2021-10-18 22:33:05,804][INFO][4447903232][speed_test_methods.py:72]Testing latency to server.
[2021-10-18 22:33:06,962][INFO][4447903232][speed_test_methods.py:68]Testing latency to google.
[2021-10-18 22:33:08,365][INFO][4447903232][geo_ip.py:63]Starting Geo IP.
[2021-10-18 22:33:08,483][ERROR][4447903232][geo_ip.py:76]Geo IP Failed.
Traceback (most recent call last):
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/site-packages/urllib3/connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: SOCKSHTTPSConnectionPool(host='api.ip.sb', port=443): Max retries exceeded with url: /geoip/ (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chinnsenn/Developments.localized/PythonProjects/SSRSpeedN-Mod/ssrspeed/utils/geo_ip.py", line 66, in IPLoc
    rep = requests.get("https://api.ip.sb/geoip/{}".format(ip),proxies = {
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: SOCKSHTTPSConnectionPool(host='api.ip.sb', port=443): Max retries exceeded with url: /geoip/ (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))
[2021-10-18 22:33:08,490][INFO][4447903232][speed_test.py:127]Node outbound IP : N/A, Geo : N/A Unknown City, N/A
[2021-10-18 22:33:08,490][INFO][4447903232][speed_test.py:135]Performing netflix test LOCAL_PORT: 1087.
[2021-10-18 22:33:08,871][ERROR][4447903232][speed_test.py:177]代理服务器连接异常：(MaxRetryError("SOCKSHTTPSConnectionPool(host='www.netflix.com', port=443): Max retries exceeded with url: /title/70242311 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))"),)
[2021-10-18 22:33:08,876][INFO][4447903232][speed_test.py:218]Performing UDP NAT Type Test
[2021-10-18 22:33:11,903][INFO][4447903232][speed_test_methods.py:44]Starting speed test with FAST
[2021-10-18 22:33:11,904][WARNING][4447903232][speed_test.py:374]Re-testing node.
[2021-10-18 22:33:11,904][INFO][4447903232][speed_test_methods.py:44]Starting speed test with FAST
[2021-10-18 22:33:12,908][INFO][4447903232][speed_test.py:242]Starting test netflix - HongKong02 [23/23]
[2021-10-18 22:33:12,917][INFO][4447903232][client_shadowsocks.py:36]Starting Shadowsocks-libev with server aznat1.xiaomai.my03.com:11311
[2021-10-18 22:33:13,923][INFO][4447903232][speed_test.py:276]Client started.
[2021-10-18 22:33:14,932][INFO][4447903232][geo_ip.py:46]Translating aznat1.xiaomai.my03.com to ipv4.
[2021-10-18 22:33:14,934][INFO][4447903232][geo_ip.py:63]Starting Geo IP.
[2021-10-18 22:33:15,284][ERROR][4447903232][geo_ip.py:76]Geo IP Failed.
Traceback (most recent call last):
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/site-packages/urllib3/connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: SOCKSHTTPSConnectionPool(host='api.ip.sb', port=443): Max retries exceeded with url: /geoip/198.18.3.54 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chinnsenn/Developments.localized/PythonProjects/SSRSpeedN-Mod/ssrspeed/utils/geo_ip.py", line 66, in IPLoc
    rep = requests.get("https://api.ip.sb/geoip/{}".format(ip),proxies = {
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: SOCKSHTTPSConnectionPool(host='api.ip.sb', port=443): Max retries exceeded with url: /geoip/198.18.3.54 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))
[2021-10-18 22:33:15,305][INFO][4447903232][speed_test.py:111]Node inbound IP : 198.18.3.54, Geo : N/A Unknown City, N/A
[2021-10-18 22:33:15,305][INFO][4447903232][speed_test_methods.py:72]Testing latency to server.
[2021-10-18 22:33:16,385][INFO][4447903232][speed_test_methods.py:68]Testing latency to google.
[2021-10-18 22:33:19,601][INFO][4447903232][geo_ip.py:63]Starting Geo IP.
[2021-10-18 22:33:19,718][ERROR][4447903232][geo_ip.py:76]Geo IP Failed.
Traceback (most recent call last):
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/site-packages/urllib3/connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: SOCKSHTTPSConnectionPool(host='api.ip.sb', port=443): Max retries exceeded with url: /geoip/ (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chinnsenn/Developments.localized/PythonProjects/SSRSpeedN-Mod/ssrspeed/utils/geo_ip.py", line 66, in IPLoc
    rep = requests.get("https://api.ip.sb/geoip/{}".format(ip),proxies = {
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: SOCKSHTTPSConnectionPool(host='api.ip.sb', port=443): Max retries exceeded with url: /geoip/ (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))
[2021-10-18 22:33:19,721][INFO][4447903232][speed_test.py:127]Node outbound IP : N/A, Geo : N/A Unknown City, N/A
[2021-10-18 22:33:19,721][INFO][4447903232][speed_test.py:135]Performing netflix test LOCAL_PORT: 1087.
[2021-10-18 22:33:19,827][ERROR][4447903232][speed_test.py:177]代理服务器连接异常：(MaxRetryError("SOCKSHTTPSConnectionPool(host='www.netflix.com', port=443): Max retries exceeded with url: /title/70242311 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))"),)
[2021-10-18 22:33:19,830][INFO][4447903232][speed_test.py:218]Performing UDP NAT Type Test
[2021-10-18 22:33:22,854][INFO][4447903232][speed_test_methods.py:44]Starting speed test with FAST
[2021-10-18 22:33:22,855][WARNING][4447903232][speed_test.py:374]Re-testing node.
[2021-10-18 22:33:22,855][INFO][4447903232][speed_test_methods.py:44]Starting speed test with FAST
[2021-10-18 22:33:23,866][INFO][4447903232][export_result.py:60]Time Used : 00:10:05
[2021-10-18 22:33:23,866][INFO][4447903232][export_result.py:46]Set colors as origin.
[2021-10-18 22:33:24,164][INFO][4447903232][export_result.py:263]Result image saved as ./results/2021-10-18-22-33-23.png
